#!/usr/local/bin/python3

import os
import sys
import logging

logging.basicConfig(level='DEBUG' if os.environ.get('LOG') == '1' else 'INFO', format='%(lineno)s:%(funcName)s:%(message)s')
logger = logging.getLogger(__name__)

input_file = 'd.in' if len(sys.argv) > 1 else 'sample.in'
with open(input_file) as f: s = f.read() 

