#!/bin/bash

[ $# -ne 1 ] && echo "need day number" && exit 1
[ -d "d$1" ] && echo "already exists" && exit 1
mkdir -p "d$1"

read -r -d '' t1 << EOM
@main def d${1}p1(args: String*): Unit =
  val lines = scala.io.Source
    .fromFile(if args.length > 0 then "d.in" else "sample.in")
    .getLines
EOM

read -r -d '' t2 << EOM
@main def d${1}p2(args: String*): Unit =
  val lines = scala.io.Source
    .fromFile(if args.length > 0 then "d.in" else "sample.in")
    .getLines
EOM

echo "$t1" > "d$1/d${1}p1.scala"
echo "$t2" > "d$1/d${1}p2.scala"
echo "init success"

